### PR TITLE
fix:  [This should be] a patch release

### PR DESCRIPTION
**Pull request by 4jamied**

### CODE REVIEW

**Review by 4jamied — COMMENTED** [review]
test review

**Review by jamiedugan — COMMENTED** [review]
test review

**Comment by 4jamied** [comment]
:warning: Warning
The ChartKop CircleCI job `run_chartkop` succeeded, but encountered **NON-FATAL WARNINGS**. These warnings mean that your chart contains violations of Procore Kubernetes policies that will soon be enforced on our clusters. While these will not currently prevent you from deploying this chart, you should consider addressing these soon.
Please review the [Chartkop results for more details.](https://circleci.com/gh/procore/chartkop/13158)

**Comment by 4jamied** [comment]
<details open>
<summary>Shopping list</summary>

* WARNING: Policy disallow-default-namespace / Rule validate-podcontroller-namespace
* WARNING: Policy require-pod-probes / Rule autogen-validate-livenessProbe-readinessProbe
* WARNING: Policy require-requests-limits / Rule autogen-validate-resources
* WARNING: Policy restrict-kubernetes-dashboard / Rule autogen-restrict-kubernetes-dashboard-label
* WARNING: Policy disallow-privilege-escalation / Rule autogen-privilege-escalation
* WARNING: Policy disallow-privileged-containers / Rule autogen-privileged-containers
* WARNING: Policy drop-cap-net-raw / Rule autogen-require-drop-cap-net-raw
* WARNING: Policy ensure-readonly-root-filesystem / Rule autogen-readonly-root-fs
* WARNING: Policy require-non-root-user / Rule autogen-run-as-non-root

</details>

**Comment by 4jamied** [comment]
:warning: Warning
The ChartKop CircleCI job `run_chartkop` succeeded, but encountered **NON-FATAL WARNINGS**. These warnings mean that your chart contains violations of Procore Kubernetes policies that will soon be enforced on our clusters. While these will not currently prevent you from deploying this chart, you should consider addressing these soon.
Please review the Circle CI job result for, **ci/circleci: run_chartkop** in the CircleCI checks section below.

📓 Note
Once all these policy violations have been corrected, Chartkop will comment again to indicate that all warnings have been addressed. Until then, please review the current run's **ci/circleci: run_chartkop** job results to see the policy warning status.

**Comment by 4jamied** [comment]
⚠️ Warning
The ChartKop CircleCI job `run_chartkop` succeeded, but encountered **NON-FATAL WARNINGS**. These warnings mean that your chart contains violations of Procore Kubernetes policies that will soon be enforced on our clusters. While these will not currently prevent you from deploying this chart, you should consider addressing these soon.
Please review the Circle CI job result for, **ci/circleci: run_chartkop** in the CircleCI checks section below.

<details closed>
<summary>Click on the arrow to the right to show a summary of the Policy Violation Warnings that were found</summary>

* WARNING: Policy disallow-default-namespace / Rule validate-podcontroller-namespace
* WARNING: Policy require-pod-probes / Rule autogen-validate-livenessProbe-readinessProbe
* WARNING: Policy require-requests-limits / Rule autogen-validate-resources
* WARNING: Policy restrict-kubernetes-dashboard / Rule autogen-restrict-kubernetes-dashboard-label
* WARNING: Policy disallow-privilege-escalation / Rule autogen-privilege-escalation
* WARNING: Policy disallow-privileged-containers / Rule autogen-privileged-containers
* WARNING: Policy drop-cap-net-raw / Rule autogen-require-drop-cap-net-raw
* WARNING: Policy ensure-readonly-root-filesystem / Rule autogen-readonly-root-fs
* WARNING: Policy require-non-root-user / Rule autogen-run-as-non-root

</details>

📓 Note
Once all these policy violations have been corrected, Chartkop will comment again to indicate that all warnings have been addressed. Until then please review the current run's **ci/circleci: run_chartkop** job results to see the policy warning status.

**Comment by 4jamied** [comment]
:warning: Warning
The ChartKop CircleCI job `run_chartkop` succeeded, but encountered **NON-FATAL WARNINGS**. These warnings mean that your chart contains violations of Procore Kubernetes policies that will soon be enforced on our clusters. While these will not currently prevent you from deploying this chart, you should consider addressing these soon.
Please review the Circle CI job result for,  [ci/circleci: run_chartkop](https://circleci.com/gh/procore/chartkop/13158).

📓 Note
Once all these policy violations have been corrected, Chartkop will comment again to indicate that all warnings have been addressed.

**Comment by 4jamied** [comment]
:warning: Warning
The ChartKop CircleCI job `run_chartkop` succeeded, but encountered **NON-FATAL WARNINGS**. These warnings mean that your chart contains violations of Procore Kubernetes policies that will soon be enforced on our clusters. While these will not currently prevent you from deploying this chart, you should consider addressing these soon.
Please review the Circle CI job result for,  [ci/circleci: run_chartkop](https://circleci.com/gh/procore/chartkop/13158)
<details closed>
<summary>Click on the arrow to the right to show a summary of the Policy Violation Warnings that were found</summary>

* WARNING: Policy disallow-default-namespace / Rule validate-podcontroller-namespace
* WARNING: Policy require-pod-probes / Rule autogen-validate-livenessProbe-readinessProbe
* WARNING: Policy require-requests-limits / Rule autogen-validate-resources
* WARNING: Policy restrict-kubernetes-dashboard / Rule autogen-restrict-kubernetes-dashboard-label
* WARNING: Policy disallow-privilege-escalation / Rule autogen-privilege-escalation
* WARNING: Policy disallow-privileged-containers / Rule autogen-privileged-containers
* WARNING: Policy drop-cap-net-raw / Rule autogen-require-drop-cap-net-raw
* WARNING: Policy ensure-readonly-root-filesystem / Rule autogen-readonly-root-fs
* WARNING: Policy require-non-root-user / Rule autogen-run-as-non-root

</details>

📓  Note
Once all these policy violations have been corrected, Chartkop will comment again to indicate that all warnings have been addressed.

**Comment by 4jamied** [comment]
🎉  Hurray!
It looks like all previous Chartkop Warnings found have been corrected.  ChartKop will notify you again if any more warnings appear.

**Pull request merged**
